# Generated by Django 5.0.10 on 2025-01-07 19:13

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dog',
            name='age',
        ),
        migrations.AddField(
            model_name='dog',
            name='last_visit',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='dog',
            name='note',
            field=models.TextField(blank=True, null=True),
        ),
    ]
